issure_tracker/accounts/urls.py
from django.urls import path
from accounts.views import logout_view, login_view, register_view, UserDetailView, UserView,\
    UserChangeView, UserPasswordChangeView

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('create/', register_view, name='create'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('users/', UserView.as_view(), name='user'),
    path('<int:pk>/change/', UserChangeView.as_view(), name='change'),
    path('password_change/', UserPasswordChangeView.as_view(), name='password_change')

]

issure_tracker/issure_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

HOMEPAGE_URL = 'project/'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('project/', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('', RedirectView.as_view(url=HOMEPAGE_URL, permanent=False)),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

issure_tracker/webapp/urls.py
from django.urls import path
from webapp.views import (
    IndexView,
    TracerView,
    TracerDeleteView,
    TracerUpdateView,
    ProjectTracerCreate,
    ProjectCreateView,
    ProjectIndexView,
    ProjectView,
    ProjectDeleteView,
    ProjectUpdateView,
    UserUpdateView
)

app_name = 'project'

urlpatterns = [
    path('tracers/', IndexView.as_view(), name='list'),
    path('<int:pk>/', TracerView.as_view(), name='view'),
    path('<int:pk>/update/', TracerUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', TracerDeleteView.as_view(), name='delete'),

    path('user/<int:pk>', UserUpdateView.as_view(), name="user_update"),

    path('project/add/', ProjectCreateView.as_view(), name='project_add'),
    path('project_tracer/<int:pk>/add/', ProjectTracerCreate.as_view(), name='project_tracer_add'),
    path('', ProjectIndexView.as_view(), name='project_list'),
    path('project/<int:pk>/', ProjectView.as_view(), name='project_view'),
    path('project/<int:pk>/update/', ProjectUpdateView.as_view(), name='project_update'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='project_delete'),

]

issure_tracker/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Profile(models.Model):
    user = models.OneToOneField(get_user_model(), related_name='profile', on_delete=models.CASCADE,
                                verbose_name='Ползователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    link = models.URLField(null=True, blank=True, verbose_name='Сылка на GitHub')
    avatar = models.ImageField(null=True, blank=True, verbose_name='Аватар', upload_to='user_pics')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name="Полное описание")

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'
        permissions = [('view_users', 'Просмотр пользоватей')]

issure_tracker/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from .models import Profile




class MyUserCreationForm(forms.ModelForm):
    password = forms.CharField(label="Пароль", strip=False, required=True, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", required=True, widget=forms.PasswordInput, strip=False)
    email = forms.CharField(required=True)
    last_name = forms.CharField(label="last_name", strip=False, required=False)
    first_name = forms.CharField(label="first_name", required=False, strip=False)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")
        last_name = cleaned_data.get("last_name")
        first_name = cleaned_data.get("first_name")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        if last_name == "" and first_name == "" :
            raise forms.ValidationError('Хотябы last_name или first_name должно быть заполнено  ')


    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'password', 'password_confirm', 'first_name', 'last_name', 'email']


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {"first_name": 'Имя', "last_name": 'Фамилия', "email":
                  'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class PasswordChangeForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user


    class Meta:
        model = get_user_model()
        fields = ['old_password', 'password', 'password_confirm']

issure_tracker/accounts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from accounts.models import Profile
from .forms import MyUserCreationForm, ProfileChangeForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.views.generic import DetailView, ListView, UpdateView
from django.contrib.auth import get_user_model, update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.paginator import Paginator
from accounts.forms import UserChangeForm

def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('project:project_list')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('project:project_list')


def register_view(request, *args, **kwargs):
    if request.method == 'POST':
        form = MyUserCreationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            Profile.objects.create(user=user)
            login(request, user)
            return redirect('project:project_list')
    else:
        form = MyUserCreationForm()
    return render(request, 'user_create.html', context={'form': form})


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 1

    def get_context_data(self, **kwargs):
        projects = self.object.projects.all()
        paginator = Paginator(projects, self.paginate_related_by, orphans=self.paginate_related_orphans)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        kwargs['page_obj'] = page
        kwargs['projects'] = page.object_list
        kwargs['is_paginate'] = page.has_other_pages()
        return super().get_context_data(**kwargs)


class UserView(PermissionRequiredMixin, ListView):
    model = get_user_model()
    template_name = 'user_list.html'
    context_object_name = 'users'
    permission_required = 'accounts.view_users'


class UserChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'


    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data (self, **kwargs: object) -> object:
        if 'profile_form' not in kwargs:
            kwargs['profile_form']=self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        response = super().form_valid(form)
        profile_form.save()
        return response

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form )
        return self.render_to_response(context)

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):

    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

issure_tracker/accounts/templates/index_accounts.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1>Вход</h1>
    <form action="{% url 'login' %}" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>
</div>
</body>
</html>

issure_tracker/accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
         content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Вход</title>
</head>
<body>
<div class="container">
    <h1>Вход</h1>
    <form action="{% url 'accounts:login' %}" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <div class="form-group">
            <label for="username" class="form-label">Имя пользователя:</label>
            <input type="text" name="username" id="username">
        </div>
        <div class="form-group">
            <label for="password" class="form-label">Пароль:</label>
            <input type="password" name="password" id="password">
        </div>
        <button type="submit">Войти</button>
    </form>
</div>
</body>
</html>

issure_tracker/accounts/templates/user_change.html
{% extends 'base.html' %}
{% block title %}Редактировать пользователя{% endblock %}

{% block menu_links %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
{#    <li><a href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a></li>#}
    <li><a href="{% url "accounts:password_change" %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>
    <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

issure_tracker/accounts/templates/user_create.html
{% extends 'base.html' %}
{% block title %}Регистрация{% endblock %}
{% block content %}
    <h1>Регистрация</h1>
    <form action="{% url "accounts:create" %}" method="post">
        {% include 'partial/form.html' with form_method='post' button_text="Зарегистрироваться" %}
    </form>

{% endblock %}

issure_tracker/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}Пользователь{% endblock %}
{#{% block menu_links %}#}
{#    <li><a href="{% url "accounts:password_change" user_obj.pk %}">Смена пароля</a></li>#}
{#    <li><a href="{% url "accounts:password_change" %}">Смена пароля</a></li>#}
{#    <li><a href="{% url 'accounts:change' user_obj.pk %}">Редактировать</a></li>#}
{#{% endblock %}#}

{% block menu %}
    {% if request.user == user_obj %}
        <li><a href="{% url 'accounts:change' user_obj.pk %}">Редактировать</a></li>
        <li><a href="{% url "accounts:password_change" %}">Смена пароля</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
    {% if user_obj.profile.avatar %}
        <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250" alt="user picture">
    {% endif %}
    <p>Имя пользователя: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>Дата рождения: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
    <p>Сылка на GitHub: {{ user_obj.profile.link }}</p>
    <p>Почта: {{ user_obj.email }}</p>

    <h2 class="text-center clear">Статьи автора:</h2>
    {% include 'partial/product_lists.html' %}
{% endblock %}

issure_tracker/accounts/templates/user_list.html
{% extends "base.html" %}
{% block content %}
{% for user in users %}
     <a href="{% url 'accounts:detail' user.pk %}">{{ user.username }} </a> </br>
{% endfor %}
{% endblock %}

issure_tracker/accounts/templates/user_password_change.html
{% extends 'base.html' %}
{% block title %}Смена пароля{% endblock %}

{% block menu_links %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>

    <li><a href="{% url "accounts:change" user_obj.pk %}">Редактирование личных данных</a></li>
{% endblock %}

{% block content %}
    <h1>Смена пароля</h1>
    {% url "accounts:password_change" as action_url %}
{#    {% url "accounts:password_change" user_obj.pk as action_url %}#}
    {% include 'partial/form.html' with action_url=action_url form_method="post" %}
{% endblock %}